"Beginning
call plug#begin('~/.vim/plugged')
	Plug 'scrooloose/nerdtree'
    Plug 'rafi/awesome-vim-colorschemes'
    Plug 'tpope/vim-surround'
call plug#end()

let mapleader=","
nnoremap <leader>v :e $MYVIMRC<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>x :x<CR>
nnoremap <leader>s :source $MYVIMRC<CR>
nnoremap <leader>c :close<CR>
nnoremap <leader>r :registers<CR>
nnoremap <leader>n :set relativenumber<CR>
nnoremap <leader>o :oldfiles<CR>

set guifont=Consolas:h13
set directory=$HOME\vimswapfiles/
syntax on
filetype plugin indent on
set autoindent
set expandtab
set tabstop=4   
set shiftwidth=4 
set backspace=2 
"set undofile "Persistent undo
colorscheme OceanicNext
