"Beginning
call plug#begin('~/.vim/plugged')
	Plug 'scrooloose/nerdtree'
    Plug 'rafi/awesome-vim-colorschemes'
    Plug 'tpope/vim-surround'
    Plug 'pprovost/vim-ps1'
    Plug 'mattn/emmet-vim'
    Plug 'flazz/vim-colorschemes'
call plug#end()

let mapleader=","
nnoremap <leader>v :e $MYVIMRC<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>x :x<CR>
nnoremap <leader>s :source $MYVIMRC<CR>
nnoremap <leader>c :close<CR>
nnoremap <leader>r :registers<CR>
nnoremap <leader>rn :set relativenumber<CR>
nnoremap <leader>nr :set norelativenumber<CR>
nnoremap <leader>o :oldfiles<CR>
nnoremap <leader>t :terminal<CR>

set guifont=Consolas:h13
set directory=$HOME\vimswapfiles/
syntax on
filetype plugin indent on
set autoindent
set expandtab
set tabstop=4   
set shiftwidth=4 
set backspace=2 
set ruler
set showcmd
set laststatus=2
colorscheme OceanicNext
